spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviematch?useSSL=false
    username: root
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect